# This is a basic workflow to help you get started with Actions

name: simple-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  preparation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GREETING: Hello

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          SUPER_SECRET: ${{secrets.EXAMPLE_SECRET}}
        run: |
          echo My Github token is ${{secrets.GITHUB_TOKEN}}
          echo My super secret is ${{env.SUPER_SECRET}}
          echo "$DAY_OF_WEEK"
          echo "$GREETING"
      - name: Run only for main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Deploying to production server on branch $GITHUB_REF"

  quality_gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    
      - uses: nrwl/nx-set-shas@v3

      - name: Install deps
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Unit test
        run: npm run test


